import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import { saveAs } from "file-saver";
import { PlanInputs } from "@/types/plan";
import { FEATURE_CATEGORIES } from "@/lib/config/features";

export async function generatePlanDOCX(planData: {
  title: string;
  inputs: PlanInputs;
  createdAt: string;
}) {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: "Product Brief",
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: planData.title,
                bold: true,
                size: 32,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Created: ${new Date(planData.createdAt).toLocaleDateString()}`,
                color: "666666",
                italics: true,
              }),
            ],
            spacing: { after: 600 },
          }),

          // Section 1: Problem & Solution
          new Paragraph({
            text: "Problem & Solution",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Problem Statement", bold: true })],
          }),
          new Paragraph({
            text: planData.inputs.problemStatement || "Not specified",
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Target User", bold: true })],
          }),
          new Paragraph({
            text: planData.inputs.targetUser || "Not specified",
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Value Proposition", bold: true })],
          }),
          new Paragraph({
            text: planData.inputs.valueProposition || "Not specified",
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Non-Goals", bold: true })],
          }),
          new Paragraph({
            text: planData.inputs.nonGoals || "Not specified",
            spacing: { after: 400 },
          }),

          // Section 2: Scope
          new Paragraph({
            text: "Scope & Complexity",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),

          ...(planData.inputs.features?.map((featureId: string) => {
            // Find label
            let label = featureId;
            for (const cat of FEATURE_CATEGORIES) {
              const found = cat.features.find((f) => f.id === featureId);
              if (found) {
                label = found.label;
                break;
              }
            }

            return new Paragraph({
              text: `• ${label}`,
              bullet: { level: 0 },
            });
          }) || []),
          new Paragraph({
            children: [
              new TextRun({ text: "Complexity Score: ", bold: true }),
              new TextRun({
                text: `${planData.inputs.complexityScore || 0}/100`,
              }),
            ],
            spacing: { before: 200, after: 400 },
          }),

          // Section 3: Tech Stack
          new Paragraph({
            text: "Strategic Alignment",
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Project Type: ", bold: true }),
              new TextRun({
                text: planData.inputs.projectType || "Not specified",
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Team Size: ", bold: true }),
              new TextRun({
                text: planData.inputs.teamSize || "Not specified",
              }),
            ],
          }),
          new Paragraph({
            children: [
              new TextRun({ text: "Recommended Stack: ", bold: true }),
              new TextRun({
                text: planData.inputs.selectedStack || "Not specified",
              }),
            ],
            spacing: { before: 200, after: 600 },
          }),

          // Footer
          new Paragraph({
            children: [
              new TextRun({
                text: "Generated by AtoZyx LaunchPad",
                color: "999999",
                size: 16,
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${planData.title.replace(/[^a-z0-9]/gi, "_")}.docx`);
}
