import jsPDF from "jspdf";
import { PlanInputs } from "@/types/plan";

export function generatePlanPDF(planData: {
  title: string;
  inputs: PlanInputs;
  createdAt: string;
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 20;

  // Helper to add text with word wrap
  const addText = (text: string, fontSize = 12, isBold = false) => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFont("helvetica", "normal");
    }

    const lines = doc.splitTextToSize(text, pageWidth - 40);
    doc.text(lines, 20, yPosition);
    yPosition += lines.length * (fontSize / 2) + 5;
  };

  // Header
  doc.setFillColor(23, 23, 23); // neutral-950
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Product Brief", 20, 25);

  // Reset colors
  doc.setTextColor(0, 0, 0);
  yPosition = 50;

  // Title
  addText(planData.title, 18, true);
  yPosition += 5;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Created: ${new Date(planData.createdAt).toLocaleDateString()}`,
    20,
    yPosition,
  );
  yPosition += 15;
  doc.setTextColor(0, 0, 0);

  // Section 1: Problem & Solution
  addText("Problem Statement", 14, true);
  addText(planData.inputs.problemStatement || "Not specified");
  yPosition += 5;

  addText("Target User", 14, true);
  addText(planData.inputs.targetUser || "Not specified");
  yPosition += 5;

  addText("Value Proposition", 14, true);
  addText(planData.inputs.valueProposition || "Not specified");
  yPosition += 5;

  addText("Non-Goals", 14, true);
  addText(planData.inputs.nonGoals || "Not specified");
  yPosition += 10;

  // Section 2: Scope
  if (planData.inputs.features && planData.inputs.features.length > 0) {
    addText("Selected Features", 14, true);
    planData.inputs.features.forEach((feature) => {
      addText(`• ${feature}`, 11);
    });
    yPosition += 5;
  }

  if (planData.inputs.complexityScore) {
    addText("Complexity Score", 14, true);
    addText(`${planData.inputs.complexityScore}/100`, 12);
    yPosition += 10;
  }

  // Section 3: Tech Stack
  if (planData.inputs.projectType) {
    addText("Project Type", 14, true);
    addText(planData.inputs.projectType, 12);
    yPosition += 5;
  }

  if (planData.inputs.teamSize) {
    addText("Team Size", 14, true);
    addText(planData.inputs.teamSize, 12);
    yPosition += 5;
  }

  if (planData.inputs.selectedStack) {
    addText("Recommended Stack", 14, true);
    addText(planData.inputs.selectedStack, 12);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by AtoZyx LaunchPad", pageWidth / 2, pageHeight - 10, {
    align: "center",
  });

  // Save
  doc.save(`${planData.title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
}
