import { getPlanByToken } from "@/lib/actions/planActions";
import { ProductBrief } from "@/components/wizard/ProductBrief";
import { notFound } from "next/navigation";
import { Metadata } from "next";

interface SharePageProps {
  params: Promise<{ token: string }>;
}

export async function generateMetadata(
  props: SharePageProps
): Promise<Metadata> {
  const params = await props.params;
  const plan = await getPlanByToken(params.token);

  if (!plan) {
    return {
      title: "Plan Not Found",
    };
  }

  return {
    title: `Product Brief: ${plan.title} | AtoZyx LaunchPad`,
    description: `A product execution plan generated by AtoZyx LaunchPad.`,
  };
}

export default async function SharePage(props: SharePageProps) {
  const params = await props.params;
  const plan = await getPlanByToken(params.token);

  if (!plan) {
    notFound();
  }

  return (
    <div className="min-h-screen bg-neutral-950 px-4 py-12">
      <div className="mx-auto max-w-4xl text-center mb-12">
        <h2 className="text-neutral-400 text-sm font-medium uppercase tracking-widest mb-2">
          Shared Product Brief
        </h2>
        <div className="flex items-center justify-center gap-2 text-white text-xl font-bold">
          <span>AtoZyx</span>
          <span className="text-neutral-500">LaunchPad</span>
        </div>
      </div>

      <ProductBrief data={plan.inputs} title={plan.title} isPublic={true} />

      <div className="mt-12 text-center text-neutral-500 text-sm">
        <p>
          &copy; {new Date().getFullYear()} AtoZyx LaunchPad. All rights
          reserved.
        </p>
      </div>
    </div>
  );
}
