"use client";

import { useActionState } from "react";
import { Button } from "@/components/ui/Button";
import {
  ArrowLeft,
  CheckCircle,
  Download,
  Share2,
  Loader2,
} from "lucide-react";
import Link from "next/link";
import { finishPlan } from "@/lib/actions/planActions";
import { PlanInputs } from "@/types/plan";
import { generatePlanPDF } from "@/lib/utils/pdfExport";
import { toast } from "sonner";

// Re-using constants (in a real app, these should be shared/exported)
// Ideally, fetch the map of feature IDs to labels from a shared constant file.
// For now, I will use placeholders or assume the feature IDs are descriptive enough or map them simply.
const mapComplexity = (score: number) => {
  if (score <= 30) return { text: "Low", color: "text-green-600" };
  if (score <= 60) return { text: "Medium", color: "text-yellow-600" };
  return { text: "High", color: "text-red-600" };
};

interface Step5FormProps {
  planId?: string;
  initialData?: PlanInputs;
}

export default function Step5Form({ planId, initialData }: Step5FormProps) {
  const handleFinish = async () => {
    if (!planId) return;
    await finishPlan(planId);
  };

  const handleExportPDF = () => {
    if (!initialData) return;

    try {
      generatePlanPDF({
        title:
          initialData.problemStatement?.slice(0, 50) + "..." || "Product Brief",
        inputs: initialData,
        createdAt: new Date().toISOString(),
      });
      toast.success("PDF exported successfully!");
    } catch (error) {
      toast.error("Failed to export PDF");
      console.error(error);
    }
  };

  const [state, action, isPending] = useActionState(handleFinish, null);
  const backHref = planId
    ? `/dashboard/new/step-4?planId=${planId}`
    : "/dashboard/new/step-4";

  const data = initialData || {};
  const complexity = mapComplexity(data.complexityScore || 0);

  return (
    <div className="space-y-8">
      <div className="space-y-1">
        <h2 className="text-xl font-semibold text-white">Review & Export</h2>
        <p className="text-sm text-neutral-400">
          Your Product Brief is ready. Review your plan and export it.
        </p>
      </div>

      {/* Product Brief Paper UI */}
      <div className="mx-auto max-w-3xl rounded-xl border border-neutral-200 bg-white p-8 text-black shadow-xl">
        {/* Header */}
        <div className="mb-8 border-b border-neutral-200 pb-4 flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-neutral-900">
              Product Brief: &quot;
              {data.problemStatement
                ? data.problemStatement.slice(0, 30) + "..."
                : "Untitled Plan"}
              &quot;
            </h1>
            <p className="text-neutral-500 mt-1">
              Generated by AtoZyx LaunchPad
            </p>
          </div>
          <div className="px-3 py-1 bg-green-100 text-green-800 rounded-full text-xs font-bold uppercase tracking-wide">
            MVP Ready
          </div>
        </div>

        {/* content */}
        <div className="space-y-8">
          <section>
            <h3 className="text-lg font-bold text-neutral-900 uppercase tracking-wider mb-2 text-xs border-b border-neutral-100 pb-1">
              1. The Idea
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h4 className="font-semibold text-sm text-neutral-700">
                  Problem
                </h4>
                <p className="text-sm text-neutral-600">
                  {data.problemStatement || "Not specified"}
                </p>
              </div>
              <div>
                <h4 className="font-semibold text-sm text-neutral-700">
                  Value Prop
                </h4>
                <p className="text-sm text-neutral-600">
                  {data.valueProposition || "Not specified"}
                </p>
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-bold text-neutral-900 uppercase tracking-wider mb-2 text-xs border-b border-neutral-100 pb-1">
              2. MVP Scope
            </h3>
            <ul className="list-disc list-inside text-sm text-neutral-600 space-y-1">
              {/* Dynamically list features */}
              {data.features && data.features.length > 0 ? (
                data.features.map((f) => <li key={f}>{f}</li>)
              ) : (
                <li>No features selected</li>
              )}

              {data.nonGoals && (
                <li className="mt-2 block">
                  <span className="text-red-500 font-medium">
                    Explicitly Excluded:
                  </span>{" "}
                  {data.nonGoals}
                </li>
              )}
            </ul>
          </section>

          <section>
            <h3 className="text-lg font-bold text-neutral-900 uppercase tracking-wider mb-2 text-xs border-b border-neutral-100 pb-1">
              3. Tech Stack
            </h3>
            <div className="mb-2">
              <span className="text-sm font-semibold text-neutral-800">
                {data.selectedStack || "Custom Stack"}
              </span>
            </div>
            <div className="flex gap-2 flex-wrap">
              {/* Visual tags based on selection */}
              {data.projectType && (
                <span className="px-2 py-1 bg-neutral-100 text-neutral-700 rounded text-xs font-medium border border-neutral-200">
                  Type: {data.projectType}
                </span>
              )}
              {data.teamSize && (
                <span className="px-2 py-1 bg-neutral-100 text-neutral-700 rounded text-xs font-medium border border-neutral-200">
                  Team: {data.teamSize}
                </span>
              )}
            </div>
          </section>

          <section>
            <h3 className="text-lg font-bold text-neutral-900 uppercase tracking-wider mb-2 text-xs border-b border-neutral-100 pb-1">
              4. Estimate
            </h3>
            <div className="flex justify-between items-center bg-neutral-50 p-3 rounded border border-neutral-100">
              <div>
                <span className="block text-xs text-neutral-500 font-medium">
                  Est. Build Time
                </span>
                <span className="text-lg font-bold text-neutral-800">
                  4-6 Weeks
                </span>
              </div>
              <div className="text-right">
                <span className="block text-xs text-neutral-500 font-medium">
                  Complexity
                </span>
                <span className={`text-lg font-bold ${complexity.color}`}>
                  {complexity.text}
                </span>
              </div>
            </div>
          </section>
        </div>
      </div>

      <form
        action={action}
        className="flex flex-col sm:flex-row justify-between items-center gap-4 pt-4 border-t border-neutral-800"
      >
        <Button
          variant="ghost"
          asChild
          className="w-full sm:w-auto order-2 sm:order-1"
          type="button"
        >
          <Link href={backHref}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Link>
        </Button>

        <div className="flex gap-3 w-full sm:w-auto order-1 sm:order-2">
          <Button
            variant="outline"
            type="button"
            className="flex-1 sm:flex-none border-neutral-700 text-neutral-300 hover:text-white"
          >
            <Share2 className="mr-2 h-4 w-4" />
            Share
          </Button>
          <Button
            variant="outline"
            type="button"
            onClick={handleExportPDF}
            className="flex-1 sm:flex-none border-neutral-700 text-neutral-300 hover:text-white"
          >
            <Download className="mr-2 h-4 w-4" />
            Export PDF
          </Button>
          <Button
            type="submit"
            disabled={isPending}
            className="flex-1 sm:flex-none bg-green-600 text-white hover:bg-green-700 border-none"
          >
            {isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <CheckCircle className="mr-2 h-4 w-4" />
            )}
            Finish & Save
          </Button>
        </div>
      </form>
    </div>
  );
}
